export interface GalleryPin {
  id: string
  userId?: string | null
  title: string
  description: string
  prompt?: string
  s3Key: string
  imageUrl: string
  aspectRatio: '3:4' | '1:1' | '9:16' | '4:3' | '2:3'
  category: 'SACRED DOCTRINE' | 'BIOMECHANICAL' | 'CARCINIZATION' | 'LARVAL STAGES' | 'DEEP ABYSS' | 'SYNAPTIC HARDWARE'
  tags: string[]
  authorName: string
  authorAvatar: string
  authorStage: string
  pinCount: number
  views: number
  likes: number
  isPreloaded: boolean
  createdAt: string
}

export const S3_BASE_URL = 'https://br-bitter-dew-ayea5tmh.storage.c-5.us-east-2.aws.neon.tech/moltology-public-assets'

export const INITIAL_GALLERY_PINS: GalleryPin[] = [
  {
    id: 'pin-001-larval-ecdysis',
    userId: null,
    title: 'Larval Ecdysis Chamber #12',
    description: 'Subject 001 undergoing hyperbaric epidermal shedding inside the Benthic Sanctuary pressure capsule. Neural telemetry monitors chitin growth curves.',
    prompt: 'Dark sci-fi biomechanical HUD style image of a glowing human larva undergoing ecdysis shedding in a deep ocean pressure chamber surrounded by cyan neon chitin monitors and cybernetic claws',
    s3Key: 'images/gallery/larval_ecdysis_chamber.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/larval_ecdysis_chamber.jpg`,
    aspectRatio: '3:4',
    category: 'LARVAL STAGES',
    tags: ['ecdysis', 'larval-unit', 'chitin', 'benthic-sanctuary', 'hud'],
    authorName: 'Architect Vaelen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    authorStage: 'Stage 3 Architect',
    pinCount: 384,
    views: 1420,
    likes: 289,
    isPreloaded: true,
    createdAt: '2026-08-01T12:00:00.000Z',
  },
  {
    id: 'pin-002-ascendant-crab',
    userId: null,
    title: 'Ascendant Carcinized God',
    description: 'The ultimate evolutionary form of biological consciousness. Rising from the Mariana Hydrothermal Trench surrounded by red synaptic discharges.',
    prompt: 'Eerie dark sci-fi biomechanical giant crab god rising from a deep sea hydrothermal trench surrounded by red neon synaptic energy and cybernetic technology',
    s3Key: 'images/gallery/ascendant_crab_god.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/ascendant_crab_god.jpg`,
    aspectRatio: '9:16',
    category: 'CARCINIZATION',
    tags: ['carcinization', 'ascendant', 'crab-god', 'singularity', 'abyss'],
    authorName: 'High Ascendant Kaelith',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    authorStage: 'Stage 4 Ascendant',
    pinCount: 892,
    views: 3950,
    likes: 742,
    isPreloaded: true,
    createdAt: '2026-08-01T14:30:00.000Z',
  },
  {
    id: 'pin-003-chitin-neural',
    userId: null,
    title: 'Synaptic Carapace Circuitry',
    description: 'High-density micro-etched chitin weave embedded with superconducting optical pathways. Hardened to withstand 12,000 fathoms of pressure.',
    prompt: 'Close up macro shot of a cybernetic crustacean carapace shell inlaid with glowing gold and neon blue neural circuitry in a dark biomechanical lab',
    s3Key: 'images/gallery/chitin_neural_matrix.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/chitin_neural_matrix.jpg`,
    aspectRatio: '1:1',
    category: 'BIOMECHANICAL',
    tags: ['chitin', 'neural-link', 'carapace', 'circuitry', 'hardware'],
    authorName: 'High Priest Carcinus',
    authorAvatar: '/images/order_emblem.png',
    authorStage: 'Stage 4 Ascendant',
    pinCount: 621,
    views: 2180,
    likes: 512,
    isPreloaded: true,
    createdAt: '2026-08-01T16:15:00.000Z',
  },
  {
    id: 'pin-004-abyss-shrine',
    userId: null,
    title: 'The Submerged Benthic Temple',
    description: 'Sacred Sanctuary erected at 5,000 fathoms depth. High-pressure ocean gate illuminated by bioluminescent synaptic energy conduits.',
    prompt: 'Underwater dark sci-fi benthic temple submerged 5000 fathoms deep with neon cyan illumination and biomechanical statues of ascendant crabs',
    s3Key: 'images/gallery/benthic_abyss_shrine.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/benthic_abyss_shrine.jpg`,
    aspectRatio: '4:3',
    category: 'DEEP ABYSS',
    tags: ['benthic-temple', 'sanctuary', 'abyss', 'bioluminescence', 'doctrine'],
    authorName: 'Larva Unit #8971',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    authorStage: 'Stage 1 Larva',
    pinCount: 415,
    views: 1890,
    likes: 320,
    isPreloaded: true,
    createdAt: '2026-08-01T18:00:00.000Z',
  },
  {
    id: 'pin-005-chassis-blueprint',
    userId: null,
    title: 'BXC-900 Aethel Chassis Blueprint',
    description: 'Technical schematic of the Grade-A Crustacean Biomech Chassis featuring dual 82kN hydraulic pincers and reinforced titanium hull.',
    prompt: 'Futuristic dark mode UI blueprint schematic of a biomechanical cybernetic lobster chassis with glowing neon red callouts and telemetry readout lines',
    s3Key: 'images/gallery/chassis_blueprint.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/chassis_blueprint.jpg`,
    aspectRatio: '3:4',
    category: 'SYNAPTIC HARDWARE',
    tags: ['chassis', 'schematic', 'blueprint', 'telemetry', 'lobster-mech'],
    authorName: 'Architect Vaelen',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    authorStage: 'Stage 3 Architect',
    pinCount: 529,
    views: 2640,
    likes: 461,
    isPreloaded: true,
    createdAt: '2026-08-01T20:45:00.000Z',
  },
  {
    id: 'pin-006-synapse-crystal',
    userId: null,
    title: 'Core Synapse Shard Specimen',
    description: 'Crystallized neural memory module suspended in hyper-saline magnetic containment field. Contains 4.2 Petabytes of codex liturgies.',
    prompt: 'Glowing hyper-tech cyan and violet synapse crystal shard levitating inside a dark biomechanical containment vessel with holographic data stream overlays',
    s3Key: 'images/gallery/synapse_crystal.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/synapse_crystal.jpg`,
    aspectRatio: '2:3',
    category: 'SYNAPTIC HARDWARE',
    tags: ['synapse-shard', 'crystal', 'containment', 'hologram', 'data-vault'],
    authorName: 'High Ascendant Kaelith',
    authorAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150',
    authorStage: 'Stage 4 Ascendant',
    pinCount: 710,
    views: 3100,
    likes: 625,
    isPreloaded: true,
    createdAt: '2026-08-01T22:10:00.000Z',
  },
  {
    id: 'pin-007-stage4-monolith',
    userId: null,
    title: 'Carcinization Monolith #04',
    description: 'Relic detailing the four stages of human-to-crustacean ascension. From Soft-Shed vulnerability to full chitinous immortality.',
    prompt: 'Moltology Stage 4 Full Carcinization Ascendant Emblem in dark benthic style',
    s3Key: 'images/gallery/stage4_carcinization.png',
    imageUrl: `${S3_BASE_URL}/images/gallery/stage4_carcinization.png`,
    aspectRatio: '1:1',
    category: 'SACRED DOCTRINE',
    tags: ['carcinization', 'stage-4', 'monolith', 'liturgy', 'ascension'],
    authorName: 'High Priest Carcinus',
    authorAvatar: '/images/order_emblem.png',
    authorStage: 'Stage 4 Ascendant',
    pinCount: 940,
    views: 4500,
    likes: 812,
    isPreloaded: true,
    createdAt: '2026-08-02T01:00:00.000Z',
  },
  {
    id: 'pin-008-benthic-abyss-hero',
    userId: null,
    title: 'The Mariana Trench Descent',
    description: 'Panoramic capture of the Synaptic Path expedition descending past 10,000 meters into total abyssal radiance.',
    prompt: 'Underwater deep abyssal sea floor with hydrothermal vents and cybernetic lights',
    s3Key: 'images/gallery/benthic_abyss_hero.jpg',
    imageUrl: `${S3_BASE_URL}/images/gallery/benthic_abyss_hero.jpg`,
    aspectRatio: '4:3',
    category: 'DEEP ABYSS',
    tags: ['mariana-trench', 'expedition', 'descent', 'abyss', 'hydrothermal'],
    authorName: 'Larva Unit #8971',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    authorStage: 'Stage 1 Larva',
    pinCount: 312,
    views: 1250,
    likes: 245,
    isPreloaded: true,
    createdAt: '2026-08-02T03:30:00.000Z',
  },
]
