import { describe, it, expect } from 'vitest'
import { getTableConfig } from 'drizzle-orm/pg-core'
import { profiles, users, userStats, routines, routineCompletions, activityEvents, changelogs, neonAuthUser, authUser, authSession, authAccount, authVerification, authJwks, aiThreads, aiMessages, blogPosts, blogComments, leads, friendRequests, friendships, suggestionDismissals, memberBonds, notifications, academyTracks, academyCourses, academyTrackCourses, academyModules, academyLessons, academyQuizQuestions, academyEnrollments, academyLessonProgress, academyCertificates, academyCertificateAwards } from './schema'

describe('Database Schema & RLS Policies', () => {
  it('exports all user-scoped and system tables', () => {
    expect(profiles).toBeDefined()
    expect(users).toBeDefined()
    expect(userStats).toBeDefined()
    expect(routines).toBeDefined()
    expect(routineCompletions).toBeDefined()
    expect(activityEvents).toBeDefined()
    expect(changelogs).toBeDefined()
    expect(neonAuthUser).toBeDefined()
    expect(authUser).toBeDefined()
    expect(authSession).toBeDefined()
    expect(authAccount).toBeDefined()
    expect(authVerification).toBeDefined()
    expect(authJwks).toBeDefined()
    expect(aiThreads).toBeDefined()
    expect(aiMessages).toBeDefined()
    expect(blogPosts).toBeDefined()
    expect(blogComments).toBeDefined()
    expect(leads).toBeDefined()
    expect(friendRequests).toBeDefined()
    expect(friendships).toBeDefined()
    expect(suggestionDismissals).toBeDefined()
    expect(memberBonds).toBeDefined()
    expect(notifications).toBeDefined()
    expect(academyTracks).toBeDefined()
    expect(academyCourses).toBeDefined()
    expect(academyTrackCourses).toBeDefined()
    expect(academyModules).toBeDefined()
    expect(academyLessons).toBeDefined()
    expect(academyQuizQuestions).toBeDefined()
    expect(academyEnrollments).toBeDefined()
    expect(academyLessonProgress).toBeDefined()
    expect(academyCertificates).toBeDefined()
    expect(academyCertificateAwards).toBeDefined()
  })

  it('uniquely constrains Better Auth provider account pairs', () => {
    const uniqueNames = getTableConfig(authAccount).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(uniqueNames).toContain('auth_account_provider_account_uidx')
  })

  it('defines required fields on friend_requests, friendships, and notifications', () => {
    expect(friendRequests.senderId).toBeDefined()
    expect(friendRequests.recipientId).toBeDefined()
    expect(friendRequests.status).toBeDefined()
    expect(friendships.userAId).toBeDefined()
    expect(friendships.userBId).toBeDefined()
    expect(suggestionDismissals.viewerId).toBeDefined()
    expect(suggestionDismissals.dismissedUserId).toBeDefined()
    expect(suggestionDismissals.createdAt).toBeDefined()
    const dismissalUniques = getTableConfig(suggestionDismissals).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(dismissalUniques).toContain('suggestion_dismissals_viewer_target_uidx')
    expect(memberBonds.fromUserId).toBeDefined()
    expect(memberBonds.toUserId).toBeDefined()
    expect(memberBonds.kind).toBeDefined()
    expect(notifications.userId).toBeDefined()
    expect(notifications.kind).toBeDefined()
    expect(notifications.sourceKey).toBeDefined()
    expect(notifications.readAt).toBeDefined()
  })

  it('defines academy catalog keys for courses, lessons, enrollments, and credentials', () => {
    const lessonUniques = getTableConfig(academyLessons).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(lessonUniques).toContain('academy_lessons_course_slug_uidx')
    const enrollmentUniques = getTableConfig(academyEnrollments).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(enrollmentUniques).toContain('academy_enrollments_user_course_uidx')
    const progressUniques = getTableConfig(academyLessonProgress).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(progressUniques).toContain('academy_lesson_progress_user_lesson_uidx')
    const awardUniques = getTableConfig(academyCertificateAwards).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(awardUniques).toContain('academy_certificate_awards_user_cert_uidx')
    expect(academyCourses.slug).toBeDefined()
    expect(academyCourses.code).toBeDefined()
    expect(academyLessons.kind).toBeDefined()
    expect(academyLessons.videoUrl).toBeDefined()
    expect(academyQuizQuestions.correctIndex).toBeDefined()
    expect(academyCertificates.scope).toBeDefined()
    expect(academyCertificateAwards.credentialId).toBeDefined()
  })

  it('defines required fields on the leads table', () => {
    expect(leads.id).toBeDefined()
    expect(leads.email).toBeDefined()
    expect(leads.source).toBeDefined()
    expect(leads.claimedPdf).toBeDefined()
    expect(leads.convertedToUser).toBeDefined()
    expect(leads.emailOptIn).toBeDefined()
    expect(leads.emailOptInAt).toBeDefined()
  })


  it('defines required fields on the profiles table', () => {
    expect(profiles.id).toBeDefined()
    expect(profiles.role).toBeDefined()
    expect(profiles.stage).toBeDefined()
    expect(profiles.moltCredits).toBeDefined()
    expect(profiles.chitinGems).toBeDefined()
    expect(profiles.emailOptIn).toBeDefined()
    expect(profiles.emailOptInAt).toBeDefined()
    expect(profiles.emailOptInSource).toBeDefined()
    expect(profiles.isSimulated).toBeDefined()
    expect(profiles.simulatedPersona).toBeDefined()
    expect(profiles.joinSource).toBeDefined()
    expect(profiles.referredByUserId).toBeDefined()
  })

  it('defines required fields on the userStats table', () => {
    expect(userStats.id).toBeDefined()
    expect(userStats.userId).toBeDefined()
    expect(userStats.pincerTorque).toBeDefined()
    expect(userStats.shellHardness).toBeDefined()
    expect(userStats.moltmaxScore).toBeDefined()
    expect(userStats.moltmaxClearance).toBeDefined()
    expect(userStats.moltmaxDimensionScores).toBeDefined()
  })

  it('defines flexible fields on the routines table', () => {
    expect(routines.id).toBeDefined()
    expect(routines.userId).toBeDefined()
    expect(routines.title).toBeDefined()
    expect(routines.timeSlot).toBeDefined()
    expect(routines.category).toBeDefined()
    expect(routines.icon).toBeDefined()
    expect(routines.recurrence).toBeDefined()
    expect(routines.streakCount).toBeDefined()
    expect(routines.lastCompletedAt).toBeDefined()
  })

  it('defines required fields on the routineCompletions table', () => {
    expect(routineCompletions.id).toBeDefined()
    expect(routineCompletions.userId).toBeDefined()
    expect(routineCompletions.taskKey).toBeDefined()
    expect(routineCompletions.completedOn).toBeDefined()
    expect(routineCompletions.completedAt).toBeDefined()
  })

  it('defines a per-member activity event log with unique source keys', () => {
    expect(activityEvents.id).toBeDefined()
    expect(activityEvents.userId).toBeDefined()
    expect(activityEvents.kind).toBeDefined()
    expect(activityEvents.title).toBeDefined()
    expect(activityEvents.detail).toBeDefined()
    expect(activityEvents.valueBadge).toBeDefined()
    expect(activityEvents.sourceKey).toBeDefined()
    expect(activityEvents.visibility).toBeDefined()
    expect(activityEvents.metadata).toBeDefined()
    expect(activityEvents.href).toBeDefined()
    expect(activityEvents.createdAt).toBeDefined()
  })

  it('defines required fields on changelogs table', () => {
    expect(changelogs.id).toBeDefined()
    expect(changelogs.slug).toBeDefined()
    expect(changelogs.slug.isUnique).toBe(true)
    expect(changelogs.version).toBeDefined()
    expect(changelogs.title).toBeDefined()
    expect(changelogs.isPublished).toBeDefined()
  })

  it('defines required fields and unique constraint on blogPosts and blogComments tables', () => {
    expect(blogPosts.id).toBeDefined()
    expect(blogPosts.slug).toBeDefined()
    expect(blogPosts.slug.isUnique).toBe(true)
    expect(blogPosts.title).toBeDefined()
    expect(blogPosts.authorRole).toBeDefined()
    expect(blogPosts.likes).toBeDefined()
    expect(blogPosts.isFeatured).toBeDefined()

    expect(blogComments.id).toBeDefined()
    expect(blogComments.postId).toBeDefined()
    expect(blogComments.content).toBeDefined()
  })

  it('keeps paid-user and current-premium flags distinct on profiles', () => {
    expect(profiles.hasPurchasedPremium).toBeDefined()
    expect(profiles.isPremium).toBeDefined()
    expect(profiles.stripeCustomerId).toBeDefined()
    expect(profiles.stripeSubscriptionId).toBeDefined()
    expect(profiles.premiumStatus).toBeDefined()
    expect(profiles.premiumPeriodEnd).toBeDefined()
    expect(profiles.premiumSyncedAt).toBeDefined()
    const uniqueNames = getTableConfig(profiles).indexes
      .filter((idx) => idx.config.unique)
      .map((idx) => idx.config.name)
    expect(uniqueNames).toContain('profiles_stripe_customer_uidx')
    expect(uniqueNames).toContain('profiles_stripe_subscription_uidx')
  })
})
