#!/usr/bin/env node
/**
 * Logic Atlas sync.
 *
 *   npm run logic:sync                     rebuild the generated atlas
 *   npm run logic:check                    report validation errors and code drift, exit 1 if any
 *   npm run logic:sync -- --accept <ids>   re-verify anchors for rule ids (comma list, or "all"), then rebuild
 *
 * Source of truth: docs/logic/domains/*.md and docs/logic/decisions/*.md.
 * Output: src/lib/server/logic-atlas.generated.ts (served to staff only).
 */
import fs from 'node:fs'
import path from 'node:path'
import matter from 'gray-matter'
import { buildAtlas, type AnchorReportRow } from './lib/logic-atlas/build'
import {
  decisionSchema,
  domainSchema,
  formatZodError,
  type DecisionInput,
  type DomainInput,
} from './lib/logic-atlas/schema'

const ROOT = process.cwd()
const LOGIC_DIR = path.join(ROOT, 'docs/logic')
const DOMAINS_DIR = path.join(LOGIC_DIR, 'domains')
const DECISIONS_DIR = path.join(LOGIC_DIR, 'decisions')
const LOCK_FILE = path.join(LOGIC_DIR, 'anchors.lock.json')
const OUTPUT_FILE = path.join(ROOT, 'src/lib/server/logic-atlas.generated.ts')
const REPO_URL = 'https://github.com/mstupp1/moltology'

const HEADER = `/**
 * Auto-generated by scripts/sync-logic-atlas.ts. Do not edit by hand.
 * Edit docs/logic/** and run \`npm run logic:sync\` (or the /logic-atlas skill).
 * Server-only: staff read it through getLogicAtlasFn.
 */
import type { LogicAtlas } from '../logic-atlas/types'

export const LOGIC_ATLAS: LogicAtlas = `

function parseArgs(argv: string[]) {
  const check = argv.includes('--check')
  const acceptIndex = argv.indexOf('--accept')
  const accept =
    acceptIndex >= 0 && argv[acceptIndex + 1]
      ? argv[acceptIndex + 1].split(',').map((value) => value.trim()).filter(Boolean)
      : []
  return { check, accept }
}

function markdownFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return []
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.md') && !name.startsWith('_'))
    .sort()
    .map((name) => path.join(dir, name))
}

function relative(file: string): string {
  return path.relative(ROOT, file)
}

function readRepoFile(file: string): string | null {
  const full = path.join(ROOT, file)
  if (!full.startsWith(ROOT) || !fs.existsSync(full) || !fs.statSync(full).isFile()) return null
  return fs.readFileSync(full, 'utf8')
}

function loadDomains(errors: string[]): DomainInput[] {
  const domains: DomainInput[] = []
  for (const file of markdownFiles(DOMAINS_DIR)) {
    const parsed = matter(fs.readFileSync(file, 'utf8'))
    const result = domainSchema.safeParse(parsed.data)
    if (!result.success) {
      errors.push(formatZodError(relative(file), result.error))
      continue
    }
    domains.push({ ...result.data, overviewMarkdown: parsed.content, file: relative(file) })
  }
  return domains
}

function loadDecisions(errors: string[]): DecisionInput[] {
  const decisions: DecisionInput[] = []
  for (const file of markdownFiles(DECISIONS_DIR)) {
    const parsed = matter(fs.readFileSync(file, 'utf8'))
    const result = decisionSchema.safeParse(parsed.data)
    if (!result.success) {
      errors.push(formatZodError(relative(file), result.error))
      continue
    }
    decisions.push({ ...result.data, bodyMarkdown: parsed.content, file: relative(file) })
  }
  return decisions
}

function loadLock(): Record<string, string> {
  if (!fs.existsSync(LOCK_FILE)) return {}
  return JSON.parse(fs.readFileSync(LOCK_FILE, 'utf8')) as Record<string, string>
}

function writeLock(lock: Record<string, string>) {
  const sorted = Object.fromEntries(Object.entries(lock).sort(([a], [b]) => a.localeCompare(b)))
  fs.writeFileSync(LOCK_FILE, `${JSON.stringify(sorted, null, 2)}\n`)
}

function localDate(): string {
  const now = new Date()
  const pad = (value: number) => String(value).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`
}

function withoutSyncDate(source: string): string {
  return source.replace(/"syncedAt": "[^"]*"/, '"syncedAt": ""')
}

function printDrift(rows: AnchorReportRow[]) {
  const drifted = rows.filter((row) => row.drift !== 'ok')
  if (drifted.length === 0) {
    console.log(`Anchors: all ${rows.length} verified.`)
    return
  }
  console.log(`Anchors needing review (${drifted.length} of ${rows.length}):`)
  for (const row of drifted) {
    console.log(`  [${row.drift}] ${row.ruleId}  ${row.file}#${row.symbol}`)
  }
}

async function main() {
  const { check, accept } = parseArgs(process.argv.slice(2))
  const errors: string[] = []
  const domains = loadDomains(errors)
  const decisions = loadDecisions(errors)
  let lock = loadLock()

  let result = await buildAtlas({
    domains,
    decisions,
    readFile: readRepoFile,
    lock,
    repoUrl: REPO_URL,
    syncedAt: localDate(),
  })

  if (accept.length > 0 && !check) {
    const all = accept.includes('all')
    const liveKeys = new Set(result.anchors.map((row) => row.key))
    const next: Record<string, string> = {}
    for (const [key, hash] of Object.entries(lock)) {
      if (liveKeys.has(key)) next[key] = hash
    }
    let accepted = 0
    for (const row of result.anchors) {
      if (!row.hash) continue
      if (all || accept.includes(row.ruleId)) {
        next[row.key] = row.hash
        accepted++
      }
    }
    lock = next
    writeLock(lock)
    console.log(`Verified ${accepted} anchor${accepted === 1 ? '' : 's'}.`)
    result = await buildAtlas({
      domains,
      decisions,
      readFile: readRepoFile,
      lock,
      repoUrl: REPO_URL,
      syncedAt: localDate(),
    })
  }

  const allErrors = [...errors, ...result.errors]
  const output = `${HEADER}${JSON.stringify(result.atlas, null, 2)}\n`
  const { stats } = result.atlas

  console.log(
    `Logic Atlas: ${stats.domains} domains, ${stats.rules} rules, ${stats.decisions} decisions, ${stats.flagged} flagged.`,
  )
  printDrift(result.anchors)
  if (allErrors.length > 0) {
    console.error(`\nValidation errors (${allErrors.length}):`)
    for (const error of allErrors) console.error(`  ${error}`)
  }

  if (check) {
    const current = fs.existsSync(OUTPUT_FILE) ? fs.readFileSync(OUTPUT_FILE, 'utf8') : ''
    const stale = withoutSyncDate(current) !== withoutSyncDate(output)
    if (stale) console.log('\nThe generated atlas is out of date. Run npm run logic:sync.')
    const drifted = result.anchors.some((row) => row.drift !== 'ok')
    process.exit(allErrors.length > 0 || drifted || stale ? 1 : 0)
  }

  if (allErrors.length > 0) {
    console.error('\nNot writing the atlas until validation errors are fixed.')
    process.exit(1)
  }
  fs.writeFileSync(OUTPUT_FILE, output)
  console.log(`\nWrote ${relative(OUTPUT_FILE)} (${Math.round(Buffer.byteLength(output) / 1024)} KB).`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
