/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HudRouteImport } from './routes/_hud'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HudChassisRouteImport } from './routes/_hud/chassis'
import { Route as HudCommunityRouteImport } from './routes/_hud/community'
import { Route as HudDashboardRouteImport } from './routes/_hud/dashboard'
import { Route as HudIsolationRouteImport } from './routes/_hud/isolation'
import { Route as HudLecturesRouteImport } from './routes/_hud/lectures'
import { Route as HudMarketRouteImport } from './routes/_hud/market'
import { Route as HudPipelineRouteImport } from './routes/_hud/pipeline'
import { Route as HudSupportRouteImport } from './routes/_hud/support'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/_hud',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HudChassisRoute = HudChassisRouteImport.update({
  id: '/chassis',
  path: '/chassis',
  getParentRoute: () => HudRoute,
} as any)
const HudCommunityRoute = HudCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => HudRoute,
} as any)
const HudDashboardRoute = HudDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HudRoute,
} as any)
const HudIsolationRoute = HudIsolationRouteImport.update({
  id: '/isolation',
  path: '/isolation',
  getParentRoute: () => HudRoute,
} as any)
const HudLecturesRoute = HudLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => HudRoute,
} as any)
const HudMarketRoute = HudMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => HudRoute,
} as any)
const HudPipelineRoute = HudPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => HudRoute,
} as any)
const HudSupportRoute = HudSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HudRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/chassis': typeof HudChassisRoute
  '/community': typeof HudCommunityRoute
  '/dashboard': typeof HudDashboardRoute
  '/isolation': typeof HudIsolationRoute
  '/lectures': typeof HudLecturesRoute
  '/market': typeof HudMarketRoute
  '/pipeline': typeof HudPipelineRoute
  '/support': typeof HudSupportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/chassis': typeof HudChassisRoute
  '/community': typeof HudCommunityRoute
  '/dashboard': typeof HudDashboardRoute
  '/isolation': typeof HudIsolationRoute
  '/lectures': typeof HudLecturesRoute
  '/market': typeof HudMarketRoute
  '/pipeline': typeof HudPipelineRoute
  '/support': typeof HudSupportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hud': typeof HudRouteWithChildren
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/_hud/chassis': typeof HudChassisRoute
  '/_hud/community': typeof HudCommunityRoute
  '/_hud/dashboard': typeof HudDashboardRoute
  '/_hud/isolation': typeof HudIsolationRoute
  '/_hud/lectures': typeof HudLecturesRoute
  '/_hud/market': typeof HudMarketRoute
  '/_hud/pipeline': typeof HudPipelineRoute
  '/_hud/support': typeof HudSupportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/login'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/chassis'
    | '/community'
    | '/dashboard'
    | '/isolation'
    | '/lectures'
    | '/market'
    | '/pipeline'
    | '/support'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/landing'
    | '/login'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/chassis'
    | '/community'
    | '/dashboard'
    | '/isolation'
    | '/lectures'
    | '/market'
    | '/pipeline'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/_hud'
    | '/auth'
    | '/landing'
    | '/login'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/_hud/chassis'
    | '/_hud/community'
    | '/_hud/dashboard'
    | '/_hud/isolation'
    | '/_hud/lectures'
    | '/_hud/market'
    | '/_hud/pipeline'
    | '/_hud/support'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HudRoute: typeof HudRouteWithChildren
  AuthRoute: typeof AuthRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hud': {
      id: '/_hud'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hud/chassis': {
      id: '/_hud/chassis'
      path: '/chassis'
      fullPath: '/chassis'
      preLoaderRoute: typeof HudChassisRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/community': {
      id: '/_hud/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof HudCommunityRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/dashboard': {
      id: '/_hud/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HudDashboardRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/isolation': {
      id: '/_hud/isolation'
      path: '/isolation'
      fullPath: '/isolation'
      preLoaderRoute: typeof HudIsolationRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/lectures': {
      id: '/_hud/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof HudLecturesRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/market': {
      id: '/_hud/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof HudMarketRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/pipeline': {
      id: '/_hud/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof HudPipelineRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/support': {
      id: '/_hud/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof HudSupportRouteImport
      parentRoute: typeof HudRoute
    }
  }
}

interface HudRouteChildren {
  HudChassisRoute: typeof HudChassisRoute
  HudCommunityRoute: typeof HudCommunityRoute
  HudDashboardRoute: typeof HudDashboardRoute
  HudIsolationRoute: typeof HudIsolationRoute
  HudLecturesRoute: typeof HudLecturesRoute
  HudMarketRoute: typeof HudMarketRoute
  HudPipelineRoute: typeof HudPipelineRoute
  HudSupportRoute: typeof HudSupportRoute
}

const HudRouteChildren: HudRouteChildren = {
  HudChassisRoute: HudChassisRoute,
  HudCommunityRoute: HudCommunityRoute,
  HudDashboardRoute: HudDashboardRoute,
  HudIsolationRoute: HudIsolationRoute,
  HudLecturesRoute: HudLecturesRoute,
  HudMarketRoute: HudMarketRoute,
  HudPipelineRoute: HudPipelineRoute,
  HudSupportRoute: HudSupportRoute,
}

const HudRouteWithChildren = HudRoute._addFileChildren(HudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HudRoute: HudRouteWithChildren,
  AuthRoute: AuthRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
