/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HudRouteImport } from './routes/_hud'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CodexDotmdRouteImport } from './routes/codex[.]md'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as JournalDotmdRouteImport } from './routes/journal[.]md'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoltmaxRouteImport } from './routes/moltmax'
import { Route as MoltmaxxingRouteImport } from './routes/moltmaxxing'
import { Route as NewsDotmdRouteImport } from './routes/news[.]md'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OrgDotmdRouteImport } from './routes/org[.]md'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacyDotmdRouteImport } from './routes/privacy[.]md'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TermsDotmdRouteImport } from './routes/terms[.]md'
import { Route as HudChassisRouteImport } from './routes/_hud/chassis'
import { Route as HudCodexRouteImport } from './routes/_hud/codex'
import { Route as HudConnectionsRouteImport } from './routes/_hud/connections'
import { Route as HudDashboardRouteImport } from './routes/_hud/dashboard'
import { Route as HudHudRouteImport } from './routes/_hud/hud'
import { Route as HudIsolationRouteImport } from './routes/_hud/isolation'
import { Route as HudLecturesRouteImport } from './routes/_hud/lectures'
import { Route as HudMarketRouteImport } from './routes/_hud/market'
import { Route as HudOracleRouteImport } from './routes/_hud/oracle'
import { Route as HudPipelineRouteImport } from './routes/_hud/pipeline'
import { Route as HudPodcastsRouteImport } from './routes/_hud/podcasts'
import { Route as HudProfileRouteImport } from './routes/_hud/profile'
import { Route as HudSearchRouteImport } from './routes/_hud/search'
import { Route as HudSettingsRouteImport } from './routes/_hud/settings'
import { Route as HudSubterraneanRouteImport } from './routes/_hud/subterranean'
import { Route as HudSupportRouteImport } from './routes/_hud/support'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as ChangelogSlugRouteImport } from './routes/changelog/$slug'
import { Route as NewsIndexRouteImport } from './routes/news/index'
import { Route as NewsSlugRouteImport } from './routes/news/$slug'
import { Route as NewsChar123slugChar125DotmdRouteImport } from './routes/news/{$slug}[.]md'
import { Route as RenderCompositeRouteImport } from './routes/render/composite'
import { Route as HudForumIndexRouteImport } from './routes/_hud/forum/index'
import { Route as HudJournalIndexRouteImport } from './routes/_hud/journal/index'
import { Route as HudJournalSlugRouteImport } from './routes/_hud/journal/$slug'
import { Route as HudMemberProfileIdRouteImport } from './routes/_hud/member/$profileId'
import { Route as HudForumCategorySlugIndexRouteImport } from './routes/_hud/forum/$categorySlug/index'
import { Route as HudForumCategorySlugTopicSlugRouteImport } from './routes/_hud/forum/$categorySlug/$topicSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HudRoute = HudRouteImport.update({
  id: '/_hud',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexDotmdRoute = CodexDotmdRouteImport.update({
  id: '/codex.md',
  path: '/codex.md',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalDotmdRoute = JournalDotmdRouteImport.update({
  id: '/journal.md',
  path: '/journal.md',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoltmaxRoute = MoltmaxRouteImport.update({
  id: '/moltmax',
  path: '/moltmax',
  getParentRoute: () => rootRouteImport,
} as any)
const MoltmaxxingRoute = MoltmaxxingRouteImport.update({
  id: '/moltmaxxing',
  path: '/moltmaxxing',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsDotmdRoute = NewsDotmdRouteImport.update({
  id: '/news.md',
  path: '/news.md',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgDotmdRoute = OrgDotmdRouteImport.update({
  id: '/org.md',
  path: '/org.md',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyDotmdRoute = PrivacyDotmdRouteImport.update({
  id: '/privacy.md',
  path: '/privacy.md',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsDotmdRoute = TermsDotmdRouteImport.update({
  id: '/terms.md',
  path: '/terms.md',
  getParentRoute: () => rootRouteImport,
} as any)
const HudChassisRoute = HudChassisRouteImport.update({
  id: '/chassis',
  path: '/chassis',
  getParentRoute: () => HudRoute,
} as any)
const HudCodexRoute = HudCodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => HudRoute,
} as any)
const HudConnectionsRoute = HudConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => HudRoute,
} as any)
const HudDashboardRoute = HudDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HudRoute,
} as any)
const HudHudRoute = HudHudRouteImport.update({
  id: '/hud',
  path: '/hud',
  getParentRoute: () => HudRoute,
} as any)
const HudIsolationRoute = HudIsolationRouteImport.update({
  id: '/isolation',
  path: '/isolation',
  getParentRoute: () => HudRoute,
} as any)
const HudLecturesRoute = HudLecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => HudRoute,
} as any)
const HudMarketRoute = HudMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => HudRoute,
} as any)
const HudOracleRoute = HudOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => HudRoute,
} as any)
const HudPipelineRoute = HudPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => HudRoute,
} as any)
const HudPodcastsRoute = HudPodcastsRouteImport.update({
  id: '/podcasts',
  path: '/podcasts',
  getParentRoute: () => HudRoute,
} as any)
const HudProfileRoute = HudProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HudRoute,
} as any)
const HudSearchRoute = HudSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HudRoute,
} as any)
const HudSettingsRoute = HudSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => HudRoute,
} as any)
const HudSubterraneanRoute = HudSubterraneanRouteImport.update({
  id: '/subterranean',
  path: '/subterranean',
  getParentRoute: () => HudRoute,
} as any)
const HudSupportRoute = HudSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HudRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/changelog/$slug',
  path: '/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsChar123slugChar125DotmdRoute =
  NewsChar123slugChar125DotmdRouteImport.update({
    id: '/news/{$slug}.md',
    path: '/news/{$slug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const RenderCompositeRoute = RenderCompositeRouteImport.update({
  id: '/render/composite',
  path: '/render/composite',
  getParentRoute: () => rootRouteImport,
} as any)
const HudForumIndexRoute = HudForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => HudRoute,
} as any)
const HudJournalIndexRoute = HudJournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => HudRoute,
} as any)
const HudJournalSlugRoute = HudJournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => HudRoute,
} as any)
const HudMemberProfileIdRoute = HudMemberProfileIdRouteImport.update({
  id: '/member/$profileId',
  path: '/member/$profileId',
  getParentRoute: () => HudRoute,
} as any)
const HudForumCategorySlugIndexRoute =
  HudForumCategorySlugIndexRouteImport.update({
    id: '/forum/$categorySlug/',
    path: '/forum/$categorySlug/',
    getParentRoute: () => HudRoute,
  } as any)
const HudForumCategorySlugTopicSlugRoute =
  HudForumCategorySlugTopicSlugRouteImport.update({
    id: '/forum/$categorySlug/$topicSlug',
    path: '/forum/$categorySlug/$topicSlug',
    getParentRoute: () => HudRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/codex.md': typeof CodexDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guide': typeof GuideRoute
  '/journal.md': typeof JournalDotmdRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/moltmax': typeof MoltmaxRoute
  '/moltmaxxing': typeof MoltmaxxingRoute
  '/news.md': typeof NewsDotmdRoute
  '/org': typeof OrgRoute
  '/org.md': typeof OrgDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.md': typeof PrivacyDotmdRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms.md': typeof TermsDotmdRoute
  '/chassis': typeof HudChassisRoute
  '/codex': typeof HudCodexRoute
  '/connections': typeof HudConnectionsRoute
  '/dashboard': typeof HudDashboardRoute
  '/hud': typeof HudHudRoute
  '/isolation': typeof HudIsolationRoute
  '/lectures': typeof HudLecturesRoute
  '/market': typeof HudMarketRoute
  '/oracle': typeof HudOracleRoute
  '/pipeline': typeof HudPipelineRoute
  '/podcasts': typeof HudPodcastsRoute
  '/profile': typeof HudProfileRoute
  '/search': typeof HudSearchRoute
  '/settings': typeof HudSettingsRoute
  '/subterranean': typeof HudSubterraneanRoute
  '/support': typeof HudSupportRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/{$slug}.md': typeof NewsChar123slugChar125DotmdRoute
  '/render/composite': typeof RenderCompositeRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/journal/$slug': typeof HudJournalSlugRoute
  '/member/$profileId': typeof HudMemberProfileIdRoute
  '/forum/': typeof HudForumIndexRoute
  '/journal/': typeof HudJournalIndexRoute
  '/forum/$categorySlug/$topicSlug': typeof HudForumCategorySlugTopicSlugRoute
  '/forum/$categorySlug/': typeof HudForumCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/codex.md': typeof CodexDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guide': typeof GuideRoute
  '/journal.md': typeof JournalDotmdRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/moltmax': typeof MoltmaxRoute
  '/moltmaxxing': typeof MoltmaxxingRoute
  '/news.md': typeof NewsDotmdRoute
  '/org': typeof OrgRoute
  '/org.md': typeof OrgDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.md': typeof PrivacyDotmdRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms.md': typeof TermsDotmdRoute
  '/chassis': typeof HudChassisRoute
  '/codex': typeof HudCodexRoute
  '/connections': typeof HudConnectionsRoute
  '/dashboard': typeof HudDashboardRoute
  '/hud': typeof HudHudRoute
  '/isolation': typeof HudIsolationRoute
  '/lectures': typeof HudLecturesRoute
  '/market': typeof HudMarketRoute
  '/oracle': typeof HudOracleRoute
  '/pipeline': typeof HudPipelineRoute
  '/podcasts': typeof HudPodcastsRoute
  '/profile': typeof HudProfileRoute
  '/search': typeof HudSearchRoute
  '/settings': typeof HudSettingsRoute
  '/subterranean': typeof HudSubterraneanRoute
  '/support': typeof HudSupportRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/{$slug}.md': typeof NewsChar123slugChar125DotmdRoute
  '/render/composite': typeof RenderCompositeRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/news': typeof NewsIndexRoute
  '/journal/$slug': typeof HudJournalSlugRoute
  '/member/$profileId': typeof HudMemberProfileIdRoute
  '/forum': typeof HudForumIndexRoute
  '/journal': typeof HudJournalIndexRoute
  '/forum/$categorySlug/$topicSlug': typeof HudForumCategorySlugTopicSlugRoute
  '/forum/$categorySlug': typeof HudForumCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_hud': typeof HudRouteWithChildren
  '/auth': typeof AuthRoute
  '/codex.md': typeof CodexDotmdRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/guide': typeof GuideRoute
  '/journal.md': typeof JournalDotmdRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/moltmax': typeof MoltmaxRoute
  '/moltmaxxing': typeof MoltmaxxingRoute
  '/news.md': typeof NewsDotmdRoute
  '/org': typeof OrgRoute
  '/org.md': typeof OrgDotmdRoute
  '/privacy': typeof PrivacyRoute
  '/privacy.md': typeof PrivacyDotmdRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/terms.md': typeof TermsDotmdRoute
  '/_hud/chassis': typeof HudChassisRoute
  '/_hud/codex': typeof HudCodexRoute
  '/_hud/connections': typeof HudConnectionsRoute
  '/_hud/dashboard': typeof HudDashboardRoute
  '/_hud/hud': typeof HudHudRoute
  '/_hud/isolation': typeof HudIsolationRoute
  '/_hud/lectures': typeof HudLecturesRoute
  '/_hud/market': typeof HudMarketRoute
  '/_hud/oracle': typeof HudOracleRoute
  '/_hud/pipeline': typeof HudPipelineRoute
  '/_hud/podcasts': typeof HudPodcastsRoute
  '/_hud/profile': typeof HudProfileRoute
  '/_hud/search': typeof HudSearchRoute
  '/_hud/settings': typeof HudSettingsRoute
  '/_hud/subterranean': typeof HudSubterraneanRoute
  '/_hud/support': typeof HudSupportRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/news/$slug': typeof NewsSlugRoute
  '/news/{$slug}.md': typeof NewsChar123slugChar125DotmdRoute
  '/render/composite': typeof RenderCompositeRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/news/': typeof NewsIndexRoute
  '/_hud/journal/$slug': typeof HudJournalSlugRoute
  '/_hud/member/$profileId': typeof HudMemberProfileIdRoute
  '/_hud/forum/': typeof HudForumIndexRoute
  '/_hud/journal/': typeof HudJournalIndexRoute
  '/_hud/forum/$categorySlug/$topicSlug': typeof HudForumCategorySlugTopicSlugRoute
  '/_hud/forum/$categorySlug/': typeof HudForumCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/codex.md'
    | '/feed.xml'
    | '/guide'
    | '/journal.md'
    | '/landing'
    | '/login'
    | '/moltmax'
    | '/moltmaxxing'
    | '/news.md'
    | '/org'
    | '/org.md'
    | '/privacy'
    | '/privacy.md'
    | '/rss.xml'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/terms.md'
    | '/chassis'
    | '/codex'
    | '/connections'
    | '/dashboard'
    | '/hud'
    | '/isolation'
    | '/lectures'
    | '/market'
    | '/oracle'
    | '/pipeline'
    | '/podcasts'
    | '/profile'
    | '/search'
    | '/settings'
    | '/subterranean'
    | '/support'
    | '/api/chat'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/news/$slug'
    | '/news/{$slug}.md'
    | '/render/composite'
    | '/blog/'
    | '/changelog/'
    | '/news/'
    | '/journal/$slug'
    | '/member/$profileId'
    | '/forum/'
    | '/journal/'
    | '/forum/$categorySlug/$topicSlug'
    | '/forum/$categorySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/codex.md'
    | '/feed.xml'
    | '/guide'
    | '/journal.md'
    | '/landing'
    | '/login'
    | '/moltmax'
    | '/moltmaxxing'
    | '/news.md'
    | '/org'
    | '/org.md'
    | '/privacy'
    | '/privacy.md'
    | '/rss.xml'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/terms.md'
    | '/chassis'
    | '/codex'
    | '/connections'
    | '/dashboard'
    | '/hud'
    | '/isolation'
    | '/lectures'
    | '/market'
    | '/oracle'
    | '/pipeline'
    | '/podcasts'
    | '/profile'
    | '/search'
    | '/settings'
    | '/subterranean'
    | '/support'
    | '/api/chat'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/news/$slug'
    | '/news/{$slug}.md'
    | '/render/composite'
    | '/blog'
    | '/changelog'
    | '/news'
    | '/journal/$slug'
    | '/member/$profileId'
    | '/forum'
    | '/journal'
    | '/forum/$categorySlug/$topicSlug'
    | '/forum/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/_hud'
    | '/auth'
    | '/codex.md'
    | '/feed.xml'
    | '/guide'
    | '/journal.md'
    | '/landing'
    | '/login'
    | '/moltmax'
    | '/moltmaxxing'
    | '/news.md'
    | '/org'
    | '/org.md'
    | '/privacy'
    | '/privacy.md'
    | '/rss.xml'
    | '/sign-in'
    | '/sign-up'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/terms.md'
    | '/_hud/chassis'
    | '/_hud/codex'
    | '/_hud/connections'
    | '/_hud/dashboard'
    | '/_hud/hud'
    | '/_hud/isolation'
    | '/_hud/lectures'
    | '/_hud/market'
    | '/_hud/oracle'
    | '/_hud/pipeline'
    | '/_hud/podcasts'
    | '/_hud/profile'
    | '/_hud/search'
    | '/_hud/settings'
    | '/_hud/subterranean'
    | '/_hud/support'
    | '/api/chat'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/news/$slug'
    | '/news/{$slug}.md'
    | '/render/composite'
    | '/blog/'
    | '/changelog/'
    | '/news/'
    | '/_hud/journal/$slug'
    | '/_hud/member/$profileId'
    | '/_hud/forum/'
    | '/_hud/journal/'
    | '/_hud/forum/$categorySlug/$topicSlug'
    | '/_hud/forum/$categorySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HudRoute: typeof HudRouteWithChildren
  AuthRoute: typeof AuthRoute
  CodexDotmdRoute: typeof CodexDotmdRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  GuideRoute: typeof GuideRoute
  JournalDotmdRoute: typeof JournalDotmdRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MoltmaxRoute: typeof MoltmaxRoute
  MoltmaxxingRoute: typeof MoltmaxxingRoute
  NewsDotmdRoute: typeof NewsDotmdRoute
  OrgRoute: typeof OrgRoute
  OrgDotmdRoute: typeof OrgDotmdRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyDotmdRoute: typeof PrivacyDotmdRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TermsDotmdRoute: typeof TermsDotmdRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  NewsSlugRoute: typeof NewsSlugRoute
  NewsChar123slugChar125DotmdRoute: typeof NewsChar123slugChar125DotmdRoute
  RenderCompositeRoute: typeof RenderCompositeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hud': {
      id: '/_hud'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex.md': {
      id: '/codex.md'
      path: '/codex.md'
      fullPath: '/codex.md'
      preLoaderRoute: typeof CodexDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal.md': {
      id: '/journal.md'
      path: '/journal.md'
      fullPath: '/journal.md'
      preLoaderRoute: typeof JournalDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moltmax': {
      id: '/moltmax'
      path: '/moltmax'
      fullPath: '/moltmax'
      preLoaderRoute: typeof MoltmaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moltmaxxing': {
      id: '/moltmaxxing'
      path: '/moltmaxxing'
      fullPath: '/moltmaxxing'
      preLoaderRoute: typeof MoltmaxxingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news.md': {
      id: '/news.md'
      path: '/news.md'
      fullPath: '/news.md'
      preLoaderRoute: typeof NewsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org.md': {
      id: '/org.md'
      path: '/org.md'
      fullPath: '/org.md'
      preLoaderRoute: typeof OrgDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy.md': {
      id: '/privacy.md'
      path: '/privacy.md'
      fullPath: '/privacy.md'
      preLoaderRoute: typeof PrivacyDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms.md': {
      id: '/terms.md'
      path: '/terms.md'
      fullPath: '/terms.md'
      preLoaderRoute: typeof TermsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hud/chassis': {
      id: '/_hud/chassis'
      path: '/chassis'
      fullPath: '/chassis'
      preLoaderRoute: typeof HudChassisRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/codex': {
      id: '/_hud/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof HudCodexRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/connections': {
      id: '/_hud/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof HudConnectionsRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/dashboard': {
      id: '/_hud/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof HudDashboardRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/hud': {
      id: '/_hud/hud'
      path: '/hud'
      fullPath: '/hud'
      preLoaderRoute: typeof HudHudRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/isolation': {
      id: '/_hud/isolation'
      path: '/isolation'
      fullPath: '/isolation'
      preLoaderRoute: typeof HudIsolationRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/lectures': {
      id: '/_hud/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof HudLecturesRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/market': {
      id: '/_hud/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof HudMarketRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/oracle': {
      id: '/_hud/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof HudOracleRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/pipeline': {
      id: '/_hud/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof HudPipelineRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/podcasts': {
      id: '/_hud/podcasts'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof HudPodcastsRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/profile': {
      id: '/_hud/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof HudProfileRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/search': {
      id: '/_hud/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof HudSearchRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/settings': {
      id: '/_hud/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof HudSettingsRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/subterranean': {
      id: '/_hud/subterranean'
      path: '/subterranean'
      fullPath: '/subterranean'
      preLoaderRoute: typeof HudSubterraneanRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/support': {
      id: '/_hud/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof HudSupportRouteImport
      parentRoute: typeof HudRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/changelog/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/{$slug}.md': {
      id: '/news/{$slug}.md'
      path: '/news/{$slug}.md'
      fullPath: '/news/{$slug}.md'
      preLoaderRoute: typeof NewsChar123slugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/composite': {
      id: '/render/composite'
      path: '/render/composite'
      fullPath: '/render/composite'
      preLoaderRoute: typeof RenderCompositeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hud/forum/': {
      id: '/_hud/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof HudForumIndexRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/journal/': {
      id: '/_hud/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof HudJournalIndexRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/journal/$slug': {
      id: '/_hud/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof HudJournalSlugRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/member/$profileId': {
      id: '/_hud/member/$profileId'
      path: '/member/$profileId'
      fullPath: '/member/$profileId'
      preLoaderRoute: typeof HudMemberProfileIdRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/forum/$categorySlug/': {
      id: '/_hud/forum/$categorySlug/'
      path: '/forum/$categorySlug'
      fullPath: '/forum/$categorySlug/'
      preLoaderRoute: typeof HudForumCategorySlugIndexRouteImport
      parentRoute: typeof HudRoute
    }
    '/_hud/forum/$categorySlug/$topicSlug': {
      id: '/_hud/forum/$categorySlug/$topicSlug'
      path: '/forum/$categorySlug/$topicSlug'
      fullPath: '/forum/$categorySlug/$topicSlug'
      preLoaderRoute: typeof HudForumCategorySlugTopicSlugRouteImport
      parentRoute: typeof HudRoute
    }
  }
}

interface HudRouteChildren {
  HudChassisRoute: typeof HudChassisRoute
  HudCodexRoute: typeof HudCodexRoute
  HudConnectionsRoute: typeof HudConnectionsRoute
  HudDashboardRoute: typeof HudDashboardRoute
  HudHudRoute: typeof HudHudRoute
  HudIsolationRoute: typeof HudIsolationRoute
  HudLecturesRoute: typeof HudLecturesRoute
  HudMarketRoute: typeof HudMarketRoute
  HudOracleRoute: typeof HudOracleRoute
  HudPipelineRoute: typeof HudPipelineRoute
  HudPodcastsRoute: typeof HudPodcastsRoute
  HudProfileRoute: typeof HudProfileRoute
  HudSearchRoute: typeof HudSearchRoute
  HudSettingsRoute: typeof HudSettingsRoute
  HudSubterraneanRoute: typeof HudSubterraneanRoute
  HudSupportRoute: typeof HudSupportRoute
  HudJournalSlugRoute: typeof HudJournalSlugRoute
  HudMemberProfileIdRoute: typeof HudMemberProfileIdRoute
  HudForumIndexRoute: typeof HudForumIndexRoute
  HudJournalIndexRoute: typeof HudJournalIndexRoute
  HudForumCategorySlugTopicSlugRoute: typeof HudForumCategorySlugTopicSlugRoute
  HudForumCategorySlugIndexRoute: typeof HudForumCategorySlugIndexRoute
}

const HudRouteChildren: HudRouteChildren = {
  HudChassisRoute: HudChassisRoute,
  HudCodexRoute: HudCodexRoute,
  HudConnectionsRoute: HudConnectionsRoute,
  HudDashboardRoute: HudDashboardRoute,
  HudHudRoute: HudHudRoute,
  HudIsolationRoute: HudIsolationRoute,
  HudLecturesRoute: HudLecturesRoute,
  HudMarketRoute: HudMarketRoute,
  HudOracleRoute: HudOracleRoute,
  HudPipelineRoute: HudPipelineRoute,
  HudPodcastsRoute: HudPodcastsRoute,
  HudProfileRoute: HudProfileRoute,
  HudSearchRoute: HudSearchRoute,
  HudSettingsRoute: HudSettingsRoute,
  HudSubterraneanRoute: HudSubterraneanRoute,
  HudSupportRoute: HudSupportRoute,
  HudJournalSlugRoute: HudJournalSlugRoute,
  HudMemberProfileIdRoute: HudMemberProfileIdRoute,
  HudForumIndexRoute: HudForumIndexRoute,
  HudJournalIndexRoute: HudJournalIndexRoute,
  HudForumCategorySlugTopicSlugRoute: HudForumCategorySlugTopicSlugRoute,
  HudForumCategorySlugIndexRoute: HudForumCategorySlugIndexRoute,
}

const HudRouteWithChildren = HudRoute._addFileChildren(HudRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HudRoute: HudRouteWithChildren,
  AuthRoute: AuthRoute,
  CodexDotmdRoute: CodexDotmdRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  GuideRoute: GuideRoute,
  JournalDotmdRoute: JournalDotmdRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MoltmaxRoute: MoltmaxRoute,
  MoltmaxxingRoute: MoltmaxxingRoute,
  NewsDotmdRoute: NewsDotmdRoute,
  OrgRoute: OrgRoute,
  OrgDotmdRoute: OrgDotmdRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyDotmdRoute: PrivacyDotmdRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TermsDotmdRoute: TermsDotmdRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  ChangelogSlugRoute: ChangelogSlugRoute,
  NewsSlugRoute: NewsSlugRoute,
  NewsChar123slugChar125DotmdRoute: NewsChar123slugChar125DotmdRoute,
  RenderCompositeRoute: RenderCompositeRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
